// <auto-generated />
using System;
using Interlog.HRTool.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interlog.HRTool.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230607144447_AddPathFilesJson")]
    partial class AddPathFilesJson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.EmployeeProfile", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("EmployeeProfile");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "en-US",
                            Name = "English (United States)"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "fr-FR",
                            Name = "French (France)"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "pt-PT",
                            Name = "Portuguese (Portugal)"
                        });
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Translation", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Translation");

                    b.HasData(
                        new
                        {
                            Key = "company.title.plural",
                            LanguageId = 1,
                            Value = "Campanies"
                        },
                        new
                        {
                            Key = "company.name",
                            LanguageId = 1,
                            Value = "Name"
                        },
                        new
                        {
                            Key = "company.departmentNumber",
                            LanguageId = 1,
                            Value = "Departments"
                        },
                        new
                        {
                            Key = "company.title",
                            LanguageId = 1,
                            Value = "Company"
                        },
                        new
                        {
                            Key = "company.delete.ErrorMessage",
                            LanguageId = 1,
                            Value = "It is not possible to delete the company!"
                        },
                        new
                        {
                            Key = "company.delete.SuccessMessage",
                            LanguageId = 1,
                            Value = "Company successfully deleted!"
                        },
                        new
                        {
                            Key = "department.title.plural",
                            LanguageId = 1,
                            Value = "Departments"
                        },
                        new
                        {
                            Key = "department.name",
                            LanguageId = 1,
                            Value = "Name"
                        },
                        new
                        {
                            Key = "department.company",
                            LanguageId = 1,
                            Value = "Company"
                        },
                        new
                        {
                            Key = "department.title",
                            LanguageId = 1,
                            Value = "Department"
                        },
                        new
                        {
                            Key = "department.delete.ErrorMessage",
                            LanguageId = 1,
                            Value = "Cannot delete the department!"
                        },
                        new
                        {
                            Key = "department.delete.successMessage",
                            LanguageId = 1,
                            Value = "Department successfully deleted!"
                        },
                        new
                        {
                            Key = "employee.title.plural",
                            LanguageId = 1,
                            Value = "Employees"
                        },
                        new
                        {
                            Key = "employee.firstName",
                            LanguageId = 1,
                            Value = "First Name"
                        },
                        new
                        {
                            Key = "employee.lastName",
                            LanguageId = 1,
                            Value = "Last Name"
                        },
                        new
                        {
                            Key = "employee.username",
                            LanguageId = 1,
                            Value = "Username"
                        },
                        new
                        {
                            Key = "employee.email",
                            LanguageId = 1,
                            Value = "Email"
                        },
                        new
                        {
                            Key = "employee.password",
                            LanguageId = 1,
                            Value = "Password"
                        },
                        new
                        {
                            Key = "employee.department",
                            LanguageId = 1,
                            Value = "Department"
                        },
                        new
                        {
                            Key = "employee.title",
                            LanguageId = 1,
                            Value = "Employee"
                        },
                        new
                        {
                            Key = "employee.profile",
                            LanguageId = 1,
                            Value = "Profiles"
                        },
                        new
                        {
                            Key = "employee.login",
                            LanguageId = 1,
                            Value = "Login"
                        },
                        new
                        {
                            Key = "profile.title.plural",
                            LanguageId = 1,
                            Value = "Profiles"
                        },
                        new
                        {
                            Key = "profile.name",
                            LanguageId = 1,
                            Value = "Name"
                        },
                        new
                        {
                            Key = "profile.employeeNumber",
                            LanguageId = 1,
                            Value = "Employees"
                        },
                        new
                        {
                            Key = "profile.profile.title",
                            LanguageId = 1,
                            Value = "Profile"
                        },
                        new
                        {
                            Key = "profile.delete.errorMessage",
                            LanguageId = 1,
                            Value = "It is not possible to delete the profile!"
                        },
                        new
                        {
                            Key = "profile.delete.successMessage",
                            LanguageId = 1,
                            Value = "Profile successfully deleted!"
                        },
                        new
                        {
                            Key = "title.edit",
                            LanguageId = 1,
                            Value = "Edit"
                        },
                        new
                        {
                            Key = "title.create",
                            LanguageId = 1,
                            Value = "Create"
                        },
                        new
                        {
                            Key = "title.delete",
                            LanguageId = 1,
                            Value = "Delete"
                        },
                        new
                        {
                            Key = "delete.confirmMessage",
                            LanguageId = 1,
                            Value = "Are you sure you want to delete this?"
                        },
                        new
                        {
                            Key = "general.button.login",
                            LanguageId = 1,
                            Value = "Login"
                        },
                        new
                        {
                            Key = "general.button.create",
                            LanguageId = 1,
                            Value = "Create"
                        },
                        new
                        {
                            Key = "general.button.createNew",
                            LanguageId = 1,
                            Value = "Create New"
                        },
                        new
                        {
                            Key = "general.button.edit",
                            LanguageId = 1,
                            Value = "Edit"
                        },
                        new
                        {
                            Key = "general.button.delete",
                            LanguageId = 1,
                            Value = "Delete"
                        },
                        new
                        {
                            Key = "general.button.save",
                            LanguageId = 1,
                            Value = "Save"
                        },
                        new
                        {
                            Key = "general.button.backToList",
                            LanguageId = 1,
                            Value = "Back To List"
                        },
                        new
                        {
                            Key = "general.button.back",
                            LanguageId = 1,
                            Value = "Back"
                        },
                        new
                        {
                            Key = "menu.campany.plural",
                            LanguageId = 1,
                            Value = "Campanies"
                        },
                        new
                        {
                            Key = "menu.department.plural",
                            LanguageId = 1,
                            Value = "Departments"
                        },
                        new
                        {
                            Key = "menu.profile.plural",
                            LanguageId = 1,
                            Value = "Profiles"
                        },
                        new
                        {
                            Key = "menu.employee.plural",
                            LanguageId = 1,
                            Value = "Employees"
                        },
                        new
                        {
                            Key = "datatables.translation.jsonfile",
                            LanguageId = 1,
                            Value = "/dist/js/en-GB.json"
                        },
                        new
                        {
                            Key = "company.title.plural",
                            LanguageId = 2,
                            Value = "Entreprises"
                        },
                        new
                        {
                            Key = "company.name",
                            LanguageId = 2,
                            Value = "Nom de l''entreprise"
                        },
                        new
                        {
                            Key = "company.departmentNumber",
                            LanguageId = 2,
                            Value = "Département"
                        },
                        new
                        {
                            Key = "company.title",
                            LanguageId = 2,
                            Value = "Entreprise"
                        },
                        new
                        {
                            Key = "company.delete.ErrorMessage",
                            LanguageId = 2,
                            Value = "Il n''est pas possible de supprimer l''entreprise!"
                        },
                        new
                        {
                            Key = "company.delete.SuccessMessage",
                            LanguageId = 2,
                            Value = "Entreprise supprimée avec succès!"
                        },
                        new
                        {
                            Key = "department.title.plural",
                            LanguageId = 2,
                            Value = "Départements"
                        },
                        new
                        {
                            Key = "department.name",
                            LanguageId = 2,
                            Value = "Nom de l''entreprise"
                        },
                        new
                        {
                            Key = "department.company",
                            LanguageId = 2,
                            Value = "Entreprise"
                        },
                        new
                        {
                            Key = "department.title",
                            LanguageId = 2,
                            Value = "Département"
                        },
                        new
                        {
                            Key = "department.delete.ErrorMessage",
                            LanguageId = 2,
                            Value = "Impossible de supprimer le département!"
                        },
                        new
                        {
                            Key = "department.delete.successMessage",
                            LanguageId = 2,
                            Value = "Département supprimé avec succès!"
                        },
                        new
                        {
                            Key = "employee.title.plural",
                            LanguageId = 2,
                            Value = "Employés"
                        },
                        new
                        {
                            Key = "employee.firstName",
                            LanguageId = 2,
                            Value = "Prénom"
                        },
                        new
                        {
                            Key = "employee.lastName",
                            LanguageId = 2,
                            Value = "Nom de famille"
                        },
                        new
                        {
                            Key = "employee.username",
                            LanguageId = 2,
                            Value = "Nom d''utilisateur"
                        },
                        new
                        {
                            Key = "employee.email",
                            LanguageId = 2,
                            Value = "Courriel"
                        },
                        new
                        {
                            Key = "employee.password",
                            LanguageId = 2,
                            Value = "Mot de passe"
                        },
                        new
                        {
                            Key = "employee.department",
                            LanguageId = 2,
                            Value = "Département"
                        },
                        new
                        {
                            Key = "employee.title",
                            LanguageId = 2,
                            Value = "Employé"
                        },
                        new
                        {
                            Key = "employee.profile",
                            LanguageId = 2,
                            Value = "Profil de l''employé"
                        },
                        new
                        {
                            Key = "employee.login",
                            LanguageId = 2,
                            Value = "Connexion"
                        },
                        new
                        {
                            Key = "profile.title.plural",
                            LanguageId = 2,
                            Value = "Profils"
                        },
                        new
                        {
                            Key = "profile.name",
                            LanguageId = 2,
                            Value = "Nom de l''entreprise"
                        },
                        new
                        {
                            Key = "profile.employeeNumber",
                            LanguageId = 2,
                            Value = "Employés"
                        },
                        new
                        {
                            Key = "profile.profile.title",
                            LanguageId = 2,
                            Value = "Profil"
                        },
                        new
                        {
                            Key = "profile.delete.errorMessage",
                            LanguageId = 2,
                            Value = "Il n''est pas possible de supprimer le profil!"
                        },
                        new
                        {
                            Key = "profile.delete.successMessage",
                            LanguageId = 2,
                            Value = "Profil supprimé avec succès!"
                        },
                        new
                        {
                            Key = "title.edit",
                            LanguageId = 2,
                            Value = "Modifier"
                        },
                        new
                        {
                            Key = "title.create",
                            LanguageId = 2,
                            Value = "Créer"
                        },
                        new
                        {
                            Key = "title.delete",
                            LanguageId = 2,
                            Value = "Supprimer"
                        },
                        new
                        {
                            Key = "delete.confirmMessage",
                            LanguageId = 2,
                            Value = "Êtes-vous sûr de vouloir supprimer ce profil?"
                        },
                        new
                        {
                            Key = "general.button.login",
                            LanguageId = 2,
                            Value = "Connexion"
                        },
                        new
                        {
                            Key = "general.button.create",
                            LanguageId = 2,
                            Value = "Créer"
                        },
                        new
                        {
                            Key = "general.button.createNew",
                            LanguageId = 2,
                            Value = "Créer Nouveau"
                        },
                        new
                        {
                            Key = "general.button.edit",
                            LanguageId = 2,
                            Value = "Editer"
                        },
                        new
                        {
                            Key = "general.button.delete",
                            LanguageId = 2,
                            Value = "Supprimer"
                        },
                        new
                        {
                            Key = "general.button.save",
                            LanguageId = 2,
                            Value = "Sauvegarder"
                        },
                        new
                        {
                            Key = "general.button.backToList",
                            LanguageId = 2,
                            Value = "Retour à la liste"
                        },
                        new
                        {
                            Key = "general.button.back",
                            LanguageId = 2,
                            Value = "Retour"
                        },
                        new
                        {
                            Key = "menu.campany.plural",
                            LanguageId = 2,
                            Value = "Entreprises"
                        },
                        new
                        {
                            Key = "menu.department.plural",
                            LanguageId = 2,
                            Value = "Départements"
                        },
                        new
                        {
                            Key = "menu.profile.plural",
                            LanguageId = 2,
                            Value = "Profils"
                        },
                        new
                        {
                            Key = "menu.employee.plural",
                            LanguageId = 2,
                            Value = "Employés"
                        },
                        new
                        {
                            Key = "datatables.translation.jsonfile",
                            LanguageId = 2,
                            Value = "/dist/js/fr-FR.json"
                        },
                        new
                        {
                            Key = "company.title.plural",
                            LanguageId = 3,
                            Value = "Empresas"
                        },
                        new
                        {
                            Key = "company.name",
                            LanguageId = 3,
                            Value = "Nome"
                        },
                        new
                        {
                            Key = "company.departmentNumber",
                            LanguageId = 3,
                            Value = "Departamentos"
                        },
                        new
                        {
                            Key = "company.title",
                            LanguageId = 3,
                            Value = "Empresa"
                        },
                        new
                        {
                            Key = "company.delete.ErrorMessage",
                            LanguageId = 3,
                            Value = "Não é possível eliminar a empresa!"
                        },
                        new
                        {
                            Key = "company.delete.SuccessMessage",
                            LanguageId = 3,
                            Value = "Empresa eliminada com sucesso!"
                        },
                        new
                        {
                            Key = "department.title.plural",
                            LanguageId = 3,
                            Value = "Departamentos"
                        },
                        new
                        {
                            Key = "department.name",
                            LanguageId = 3,
                            Value = "Nome da empresa"
                        },
                        new
                        {
                            Key = "department.company",
                            LanguageId = 3,
                            Value = "Empresa"
                        },
                        new
                        {
                            Key = "department.title",
                            LanguageId = 3,
                            Value = "Departamento"
                        },
                        new
                        {
                            Key = "department.delete.ErrorMessage",
                            LanguageId = 3,
                            Value = "Não é possível eliminar o departamento!"
                        },
                        new
                        {
                            Key = "department.delete.successMessage",
                            LanguageId = 3,
                            Value = "Departamento eliminado com sucesso!"
                        },
                        new
                        {
                            Key = "employee.title.plural",
                            LanguageId = 3,
                            Value = "Funcionários"
                        },
                        new
                        {
                            Key = "employee.firstName",
                            LanguageId = 3,
                            Value = "Nome"
                        },
                        new
                        {
                            Key = "employee.lastName",
                            LanguageId = 3,
                            Value = "Apelido"
                        },
                        new
                        {
                            Key = "employee.username",
                            LanguageId = 3,
                            Value = "Nome de utilizador"
                        },
                        new
                        {
                            Key = "employee.email",
                            LanguageId = 3,
                            Value = "Email"
                        },
                        new
                        {
                            Key = "employee.password",
                            LanguageId = 3,
                            Value = "Palavra-passe"
                        },
                        new
                        {
                            Key = "employee.department",
                            LanguageId = 3,
                            Value = "Departamento"
                        },
                        new
                        {
                            Key = "employee.title",
                            LanguageId = 3,
                            Value = "Funcionário"
                        },
                        new
                        {
                            Key = "employee.profile",
                            LanguageId = 3,
                            Value = "Perfis"
                        },
                        new
                        {
                            Key = "employee.login",
                            LanguageId = 3,
                            Value = "Iniciar sessão"
                        },
                        new
                        {
                            Key = "profile.title.plural",
                            LanguageId = 3,
                            Value = "Perfis"
                        },
                        new
                        {
                            Key = "profile.name",
                            LanguageId = 3,
                            Value = "Nome"
                        },
                        new
                        {
                            Key = "profile.employeeNumber",
                            LanguageId = 3,
                            Value = "Funcionários"
                        },
                        new
                        {
                            Key = "profile.profile.title",
                            LanguageId = 3,
                            Value = "Perfil"
                        },
                        new
                        {
                            Key = "profile.delete.errorMessage",
                            LanguageId = 3,
                            Value = "Il n''Não é possível eliminar o perfil!"
                        },
                        new
                        {
                            Key = "profile.delete.successMessage",
                            LanguageId = 3,
                            Value = "Perfil eliminado com sucesso!"
                        },
                        new
                        {
                            Key = "title.edit",
                            LanguageId = 3,
                            Value = "Editar"
                        },
                        new
                        {
                            Key = "title.create",
                            LanguageId = 3,
                            Value = "Criar"
                        },
                        new
                        {
                            Key = "title.delete",
                            LanguageId = 3,
                            Value = "Eliminar"
                        },
                        new
                        {
                            Key = "delete.confirmMessage",
                            LanguageId = 3,
                            Value = "Tem a certeza de que pretende apagar este perfil?"
                        },
                        new
                        {
                            Key = "general.button.login",
                            LanguageId = 3,
                            Value = "Iniciar sessão"
                        },
                        new
                        {
                            Key = "general.button.create",
                            LanguageId = 3,
                            Value = "Criar"
                        },
                        new
                        {
                            Key = "general.button.createNew",
                            LanguageId = 3,
                            Value = "Criar Novo"
                        },
                        new
                        {
                            Key = "general.button.edit",
                            LanguageId = 3,
                            Value = "Editar"
                        },
                        new
                        {
                            Key = "general.button.delete",
                            LanguageId = 3,
                            Value = "Eliminar"
                        },
                        new
                        {
                            Key = "general.button.save",
                            LanguageId = 3,
                            Value = "Salvar"
                        },
                        new
                        {
                            Key = "general.button.backToList",
                            LanguageId = 3,
                            Value = "Voltar à lista"
                        },
                        new
                        {
                            Key = "general.button.back",
                            LanguageId = 3,
                            Value = "Voltar atrás"
                        },
                        new
                        {
                            Key = "menu.campany.plural",
                            LanguageId = 3,
                            Value = "Empresas"
                        },
                        new
                        {
                            Key = "menu.department.plural",
                            LanguageId = 3,
                            Value = "Departamentos"
                        },
                        new
                        {
                            Key = "menu.profile.plural",
                            LanguageId = 3,
                            Value = "Perfis"
                        },
                        new
                        {
                            Key = "menu.employee.plural",
                            LanguageId = 3,
                            Value = "Funcionários"
                        },
                        new
                        {
                            Key = "datatables.translation.jsonfile",
                            LanguageId = 3,
                            Value = "/dist/js/pt-PT.json"
                        });
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Department", b =>
                {
                    b.HasOne("Interlog.HRTool.Data.Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Employee", b =>
                {
                    b.HasOne("Interlog.HRTool.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.EmployeeProfile", b =>
                {
                    b.HasOne("Interlog.HRTool.Data.Models.Employee", "Employee")
                        .WithMany("EmployeeProfiles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Interlog.HRTool.Data.Models.Profile", "Profile")
                        .WithMany("EmployeeProfiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Translation", b =>
                {
                    b.HasOne("Interlog.HRTool.Data.Models.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Employee", b =>
                {
                    b.Navigation("EmployeeProfiles");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Interlog.HRTool.Data.Models.Profile", b =>
                {
                    b.Navigation("EmployeeProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
